### ISSUE TITLE
Fix slight misalignment between raster and vector data (1-2 pixels)

### ISSUE THREAD

**Issue by Burdmann** [bitknox/Raven#20]

**Comment by Mansin-ITU** [comment]
In Sedona they convert geometries to have the same coordinate reference system. Both the GeoTools classes GridCoverage2D and Geometry contains a srid which tells what crs is used.

[Function to convert to same CRS](https://github.com/apache/sedona/blob/8e9a696ae63ccc927de98fba2600acb8b73ad6ef/common/src/main/java/org/apache/sedona/common/FunctionsGeoTools.java#L64)
